//1.first()
console.log($('li').first());
//2.last()
console.log($('li').last());
//3.eq(),索引从0开始
console.log($('li').eq(3));
//4.next(),从span标签下一个元素
console.log($('span').next());
//5.nextAll()
console.log($('span').nextAll());
//6.prev(),指定元素的前一个元素
console.log($('span').prev());
//7.prevAll(),指定元素之前的所有元素
console.log($('span').prevAll());
//8.parent()获取指定元素的父元素
console.log($('span').parent());
//9.parents(),获取元素所有父级元素
console.log($('span').parents());
//10.siblings(),拿到该元素所有兄弟元素
console.log($('span').siblings());
//11.find(选择器)，满足后代所有满足要求的元素
console.log($('ul').find('i'));